-- phpMyAdmin SQL Dump
-- version 4.8.0.1
-- https://www.phpmyadmin.net/
--
-- Počítač: 127.0.0.1
-- Vytvořeno: Pát 09. říj 2020, 10:03
-- Verze serveru: 10.1.32-MariaDB
-- Verze PHP: 7.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Databáze: `oa_maturitni_cetba`
--

-- --------------------------------------------------------

--
-- Struktura tabulky `cetba`
--

CREATE TABLE `cetba` (
  `id` int(11) NOT NULL,
  `nazev` varchar(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `autor` varchar(255) CHARACTER SET utf32 COLLATE utf32_czech_ci DEFAULT NULL,
  `anotace` text CHARACTER SET utf8 COLLATE utf8_czech_ci,
  `obrazek` varchar(255) CHARACTER SET utf8 COLLATE utf8_czech_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Vypisuji data pro tabulku `cetba`
--

INSERT INTO `cetba` (`id`, `nazev`, `autor`, `anotace`, `obrazek`) VALUES
(1, 'Figarova svatba', 'Beaumarchais Pierre', 'Šlechtický sukničkář, který nemá opravdu nic na práci, jeho hluboce zklamaná manželka a s nimi komorník a komorná, jež překračují zařazení mezi služebnictvo až k úrovni spoluhráčů a protihráčů, to jsou hlavní postavy Mozartovy opery Figarova svatba, jak je v nové, příjemně konvenční inscenaci pražského Národního divadla stvořila režisérka Magdalena Švecová. Soudě podle premiéry, ani hudební nastudování nevybočuje z obvyklých rámců.', 'figarova_svatba.jpg'),
(2, 'Dekameron', 'Boccaccio Giovanni', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(3, 'Co bůh? Co člověk?', 'Bridel Bedřich', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(4, 'Božská komedie', 'Dante Alighieri', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(5, 'Jakub fatalista', 'Diderot Denis', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(6, 'Jeptiška', 'Diderot Denis', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(7, 'Utrpení mladého Werthera', 'Goethe Johann Wolfgang', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(8, 'Sluha dvou pánů', 'Goldoni Carlo', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(9, 'Odysseia', 'Homér', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(10, 'Labyrint světa a ráj srdce', 'Komenský Jan Ámos', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(11, 'Tartuffe', 'Moliere', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(12, 'Píseň o Rolandovi', '', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(13, 'Hamlet', 'Shakespeare William', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(14, 'Othello', 'Shakespeare William', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(15, 'Romeo a Julie', 'Shakespeare William', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(16, 'Loupežníci', 'Schiller Friedrich', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(17, 'Antigona', 'Sofokles', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(18, 'Závěť', 'Villon Fancois', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(19, 'Candide', 'Voltaire', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(20, 'Život svaté kateřiny', '', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(21, 'Svatý Xaverius', 'Arbes Jakub', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(22, 'Zázračná madona', 'Arbes Jakub', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(23, 'Otec Goriot', 'Balzac Honoré de', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(24, 'Evženie Grandetová', 'Balzac Honoré de', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(25, 'Květy zla', 'Baudelaire Charles', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(26, 'Král Lávra + Křest sv. Vladimíra + Tyrolské elegie', 'Borovský Karel Havlíček', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(27, 'Nový epochální válet pana Broučka', 'Čech Svatopluk', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(28, 'Tři sestry', 'Čechov Anton Pavlovič', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(29, 'Racek', 'Čechov Anton Pavlovič', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(30, 'Višňový sad', 'Čechov Anton Pavlovič', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(31, 'Ohlasy', 'Čelakovský František ladislav', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL),
(32, 'Oliver Twist', 'Dickens Charles', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam erat volutpat. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam sit amet magna in magna gravida vehicula. Etiam egestas wisi a erat. Et harum quidem rerum facilis est et expedita distinctio. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam neque. Curabitur sagittis hendrerit ante. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Integer vulputate sem a nibh rutrum consequat. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Curabitur sagittis hendrerit ante. Phasellus et lorem id felis nonummy placerat. Integer tempor.', NULL);

-- --------------------------------------------------------

--
-- Struktura tabulky `menu`
--

CREATE TABLE `menu` (
  `id` int(11) NOT NULL,
  `nazev` varchar(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL,
  `displej_nazev` varchar(255) CHARACTER SET utf8 COLLATE utf8_czech_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Vypisuji data pro tabulku `menu`
--

INSERT INTO `menu` (`id`, `nazev`, `displej_nazev`) VALUES
(1, 'home', 'Domů'),
(2, 'autori', 'Autoři'),
(3, 'dila', 'Díla');

--
-- Klíče pro exportované tabulky
--

--
-- Klíče pro tabulku `cetba`
--
ALTER TABLE `cetba`
  ADD PRIMARY KEY (`id`);

--
-- Klíče pro tabulku `menu`
--
ALTER TABLE `menu`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pro tabulky
--

--
-- AUTO_INCREMENT pro tabulku `cetba`
--
ALTER TABLE `cetba`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- AUTO_INCREMENT pro tabulku `menu`
--
ALTER TABLE `menu`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
